---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      name: hermes
      component: app
      tier: backend
  template:
    metadata:
      labels:
        name: hermes
        component: app
        tier: backend
    spec:
      containers:
      - name: hermes
        image: rancherlab.operator.com/hermes:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: KAFKA
            valueFrom:
              configMapKeyRef:
                name: hermes
                key: kafka
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 200m
      imagePullSecrets:
        - name: gitlab
